    processor 6502
    org $200
    INCDIR "../../lib"
    INCLUDE "STRUCMAC.ASM"

MEMORY = $5432

    RTS_IF_MEM_LOC MEMORY, IS_POS
    RTS_IF_MEM_LOC MEMORY, IS_NEG
    RTS_IF_MEM_LOC MEMORY, IS_0
    RTS_IF_MEM_LOC MEMORY, IS_NON_0
