    PROCESSOR 6502
    org $200
    INCDIR ../../lib
    INCLUDE STRUCMAC.ASM

MEMORY = $4056

    RTS_IF_BIT MEMORY, 4, IS_LOW
    RTS_IF_BIT MEMORY, 2, IS_HIGH
    RTS_IF_BIT MEMORY, 6, IS_HIGH
    RTS_IF_BIT MEMORY, 6, IS_LOW
    RTS_IF_BIT MEMORY, 7, IS_HIGH
    RTS_IF_BIT MEMORY, 7, IS_LOW
